project:
  type: website
  output-dir: docs
toc: true
number-sections: true
format:
  html:
    toc: true
    theme:
      - cosmo
execute:
  cache: true
website:
  title: "N2T Metrics"
  sidebar:
    style: "docked"
    contents: 
      - href: index.qmd
        text: Home
      - section: "2022"
        contents:
          - june.qmd
          - july.qmd
          - august.qmd
          - september.qmd
          - october.qmd
